[package]
name = "v_name_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
rand = "0.9.2"
reqwest = "0.12.25"
tokio =  { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
